---
title: "eigenmove-structure"
format: html
editor: visual
---

# Functions

+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| Name                  | Description                                                                                                                                                                                             | Input types                                                                                                                                      | Output types                                                                  |
+=======================+=========================================================================================================================================================================================================+==================================================================================================================================================+===============================================================================+
| em_simlandscape       | Builds a simple landscape image via Gaussian processes                                                                                                                                                  | parameters (width, height, patch_scale)                                                                                                          | em_landscape (df with 3 columns, x,y,qual)                                    |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_loadlandscape      | Converts an image of a landscape into a landscape object type                                                                                                                                           | raster image                                                                                                                                     | landscape                                                                     |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_randomwalk         | Functional that builds a discrete movement model based on simple movement rules                                                                                                                         | parameters (step_length, step_speed, preference)                                                                                                 | movemodel (function)                                                          |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_movemodel          | Describes movement on a landscape in discrete or continuous time                                                                                                                                        |                                                                                                                                                  | movemodel (function)                                                          |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_loadgenerator      | Applies a pre-existing generator to a landscape image                                                                                                                                                   | landscape                                                                                                                                        | landscape                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | generator                                                                                                                                        | generator                                                                     |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_buildgenerator     | Builds a generator based on a movement model and landscape image                                                                                                                                        | landscape                                                                                                                                        | landscape                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | movemodel                                                                                                                                        | generator                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | parameters (discrete/continuous, neighborhood size, )                                                                                            |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_simmove            | Simulates movement on a landscape image                                                                                                                                                                 | landscape                                                                                                                                        | landscape                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | generator OR eigenmove                                                                                                                           | generator                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | parameters (steps, replicates, origins, )                                                                                                        | paths                                                                         |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_probmove           | Calculates the probability (or approximate probability) of moving from specified starting to ending locations after a certain amount of time                                                            | Has methods for generator and eigenmove classes                                                                                                  |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_probmove.generator |                                                                                                                                                                                                         | generator                                                                                                                                        | Either:                                                                       |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | eval_at: one of:                                                                                                                                 | a\) array of probabilities (dims length(start)xlength(end) X length(times) OR |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | a list, with entries “start”, “end”, and “times”. Will evaluate probabilies of moving from all start locations to all end locations at all times | b\) vector of probabilities associated with the tibble.                       |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | a tibble with columns “start”, “end” and “time”. Will evaluate movement probabilities for each row of the tibble                                 |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_probmove.eigenmove |                                                                                                                                                                                                         | eigenmove                                                                                                                                        | Either:                                                                       |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | eval_at: one of:                                                                                                                                 | a\) array of probabilities (dims length(start)xlength(end) X length(times) OR |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | a list, with entries “start”, “end”, and “times”. Will evaluate probabilies of moving from all start locations to all end locations at all times | b\) vector of probabilities associated with the tibble.                       |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | a tibble with columns “start”, “end” and “time”. Will evaluate movement probabilities for each row of the tibble                                 |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_eigenmove          | Calculates lower dimensional approximations of movement on landscape images, for use with other functions                                                                                               | landscape                                                                                                                                        | eigenmove                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | generator                                                                                                                                        |                                                                               |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | k (number of eigenvectors to use)                                                                                                                |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_cluster            | Clusters locations on a landscape image into patches                                                                                                                                                    | landscape OR eigenmove                                                                                                                           | landscape                                                                     |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | dist_method (type of distance function to use)                                                                                                   | patches                                                                       |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | clust_method                                                                                                                                     |                                                                               |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | parameters (clust_type, n_clusts, epsilon, )                                                                                                     |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| calculate_eigs        | Internal function that calculates QR decomposition, eigenvalues, left or right eigenvectors, stationary distribution                                                                                    | generator                                                                                                                                        | eigslist                                                                      |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | k                                                                                                                                                |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_plot               | Plotting function                                                                                                                                                                                       | landscape OR generator OR paths OR movelist OR patches                                                                                           | plot                                                                          |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | parameters (plot_type = (plain, patches, path(s), vector field), ...)                                                                            |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_dist.landscape     | Creates a distance function that can return a distance between two or more specified locations of a given location                                                                                      | landscape object                                                                                                                                 | distfunc                                                                      |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | method: one of “euclidean” or “taxicab” or “geodesic”                                                                                            |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| em_dist.eigenmove     | Creates a distance function that can return a movement distance between two or more specified locations of a given location, depending on the specified parameters of the movement model and time scale | eigenmove object                                                                                                                                 | distfunc                                                                      |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | method: one of “instant”, “average”, or “lifetime”                                                                                               |                                                                               |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | timescale (default = 1): scalar, which specifies the relevant parameter (either tau, T, or average lifespan (1/m), depending on method chosen).  |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| distfunc              | Evaluates distances between pairs of locations                                                                                                                                                          | eigenmove or landscape                                                                                                                           | dists                                                                         |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | method: specified by em_dist                                                                                                                     |                                                                               |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | timescale: specified by em_dist.eigenmove                                                                                                        |                                                                               |
|                       |                                                                                                                                                                                                         |                                                                                                                                                  |                                                                               |
|                       |                                                                                                                                                                                                         | parameter: specified by em_dist.eigenmove                                                                                                        |                                                                               |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+

# Objects

+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| Object/Class                      | Description                                                                                                                                               | Stored data                                                                | Methods              |
+===================================+===========================================================================================================================================================+============================================================================+======================+
| landscape                         | Describes a landscape (a set of sites with spatial locations and associated features and boundaries that might influence movement)                        | n: total number of stored sites                                            | print.landscape      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | sites: one of:                                                             | summary.landscape    |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | matrix (2 columns, 1 for x and 1 for y of sites)                           | plot.landscape       |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | sfc (POINT or POLYGON types only)                                          | downscale.landscape  |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | adjacency graph (saying which sites neighbour which)                       | em_dist.landscape    |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | features (optional): one of:                                               |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | tibble (with n rows and columns for each property)                         |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | list of rasters (maybe?)                                                   |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | boundaries (optional; features that are impassible to movement): sf object |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| movemodel                         | An object that estimates the rates of movement between two different locations given a set of inputs                                                      | Not sure of the best way of storing this                                   |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| generator                         | Describes pairwise movement rates                                                                                                                         | one of:                                                                    | print.generator      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | matrix                                                                     | summary.generator    |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | dgCMatrix                                                                  | plot.generator       |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | function                                                                   |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| paths                             | Describes steps taken on a landscape image                                                                                                                | tibble with columns:                                                       | print.paths          |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | time                                                                       | summary.paths        |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | replicate                                                                  | plot.paths           |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | location                                                                   | resim.paths          |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | landscape object                                                           |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| patches                           | Describes clusters of points on a landscape image                                                                                                         | vector (and matrix if want to store multiple sets of patches?)             | print.patches        |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           |                                                                            | summary.patches      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           |                                                                            | plot.patches         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigenmove                         | The low-rank approximation of a Markov-Chain random walk model                                                                                            | landscape (optional)                                                       | em_simpath.eigenmove |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | continuous (TRUE or FALSE)                                                 | em_cluster.eigenmove |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | k                                                                          | em_dist.eigenmove    |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | eigs (an [eiglist]{.underline} object)                                     | summary.eigenmove    |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| dists                             | Describes distances between pairs of points. Can be actual (e.g., euclidean) or lower-dimensional approximations (e.g., instantaneous encounter distance) |                                                                            |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| movelist\$inst_encounter          | Matrix of instantaneous encounter probabilities between individuals starting in origins x,y over time delay T                                             |                                                                            |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| movelist\$avg_interaction         | Matrix of average interaction rates per unit time between individuals starting in origins x,y over time span t                                            |                                                                            |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| movelist\$Lavg_interaction        | Matrix of interaction rate per average lifespan (1/m) between individuals starting in origins x,y with mortality m                                        |                                                                            |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist                          | not sure how to classify this and what follows                                                                                                            |                                                                            |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist\$Qphi                    | kxn orthonormal matrix that when right multiplied by Rphi gives Phi                                                                                       | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist\$Rphi                    | nxk upper triangular matrix that when left multiplied by Qphi gives Phi                                                                                   | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eiglist\$Lambda                   | nxn diagonal matrix of eigenvalues in ascending order from most negative to 0                                                                             | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Phi                                                                        |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Lambda                                                                     |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist\$Phi                     | nxk matrix describing the k-to-n leading column eigenvectors of generatormat                                                                              | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Phi                                                                        |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | stationary_distribution                                                    |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist\$Psi                     | nxk matrix describing the k-to-n leading row eigenvectors of generatormat                                                                                 | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Phi                                                                        |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | stationary_distribution                                                    |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Psi                                                                        |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+
| eigslist\$stationary_distribution | n length vector describing the long-term occupancy of the landscape                                                                                       | Qphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Rphi                                                                       |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | Phi                                                                        |                      |
|                                   |                                                                                                                                                           |                                                                            |                      |
|                                   |                                                                                                                                                           | stationary_distribution                                                    |                      |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------+----------------------+

# Methods

+-------------+--------------+--------------------------+
| Name        | Type         | Options                  |
+=============+==============+==========================+
| Print       | movemodel    |                          |
+-------------+--------------+--------------------------+
|             | landscape    |                          |
+-------------+--------------+--------------------------+
|             | generatormat |                          |
+-------------+--------------+--------------------------+
|             | paths        |                          |
+-------------+--------------+--------------------------+
|             | movelist     |                          |
+-------------+--------------+--------------------------+
|             | patches      |                          |
+-------------+--------------+--------------------------+
| summary     | movemodel    |                          |
+-------------+--------------+--------------------------+
|             | landscape    |                          |
+-------------+--------------+--------------------------+
|             | generatormat |                          |
+-------------+--------------+--------------------------+
|             | paths        |                          |
+-------------+--------------+--------------------------+
|             | movelist     |                          |
+-------------+--------------+--------------------------+
|             | patches      |                          |
+-------------+--------------+--------------------------+
| plot        | landscape    |                          |
+-------------+--------------+--------------------------+
|             | generatormat | vector field             |
+-------------+--------------+--------------------------+
|             | paths        | show/hide replicates     |
+-------------+--------------+--------------------------+
|             | movelist     | vector field             |
|             |              |                          |
|             |              | long term residency      |
|             |              |                          |
|             |              | inst. encounter heatmap  |
|             |              |                          |
|             |              | avg. interaction heatmap |
+-------------+--------------+--------------------------+
|             | patches      | colorblind friendly      |
|             |              |                          |
|             |              | show patch numbers       |
+-------------+--------------+--------------------------+
| downscale   | landscape    |                          |
+-------------+--------------+--------------------------+
| resim       | paths        | resimulate paths         |
+-------------+--------------+--------------------------+
| cluster     | generatormat |                          |
+-------------+--------------+--------------------------+
|             | movelist     |                          |
+-------------+--------------+--------------------------+
