---
title: "spencer-dev-notebook"
author: "Spencer"
format: html
editor: visual
---

Questions:

- For any functions with multiple output types (e.g., `em_loadgenerator()`) how should their outputs be organized? A list?

To do:

- In `eigenmove-vignette` either use `rescale_landscape()` or hardcode in assigning qualities to intensity values of pixels. Assigning qualities is no longer included in `em_loadlandscape()`.

#### Aug 8 2026

Started `building-functions` branch to work on coding eigenmove functions according to what's written in the shared canva whiteboard and zulip correspondence. Will borrow what's possible from existing functions, looking first to Eric's updated code from the `metapopulations-and-movement-models` repository.

#### Aug 10 2026

Added `em_loadlandscape` as a function to canva whiteboard. Transferred canva table to a .qmd in this repo: eigenmove-structure.qmd.

Added `em_loadlandscape` to functions.R. Problem is that we are loading a landscape and assigning qualities in generate-examples.R.

Solution is to just code in the example vignette habitat qualities.

```{r}
source("../R/functions.R")
a <- em_loadlandscape("../dev/gp-example.png", keep_channels = TRUE)
head(a)
```

So `em_loadlandscape()` is working with and without keep channels. generate-landscape-vignette.Rmd is still fine because it never used loadlandscape() in the first place. When I write eigenmove-vignette.Rmd I will probably have to just hardcode in assigning qualities to intensity values (or maybe use that rescale_landscape() function?)
